huggingface/community-events

huggan/pytorch/pix2pix/README.md
huggan/pytorch/pix2pix/modeling_pix2pix.py
huggan/pytorch/pix2pix/train.py
huggan/utils/push_dataset.py

This PR adds an example script for pix2pix.
To do:

Add pix2pix (PyTorch)

---

huggan/pytorch/dcgan/train.py

I wanted to run the script using Accelerate, so I did the steps explained in the docs:
`accelerate config
`
then
`accelerate launch train.py`
however, it only seems to use a single GPU, even though 2 are available.
cc'ing @sgugger

[DCGAN] Make script work on multiple GPUs

---

huggan/pytorch/dcgan/README.md
huggan/pytorch/pggan/modeling_pggan.py
huggan/pytorch/pggan/train.py
huggan/pytorch/pggan/utils.py
huggan/pytorch/pix2pix/README.md
huggan/pytorch/pix2pix/modeling_pix2pix.py
huggan/pytorch/pix2pix/train.py

This PR adds support to run pix2pix's training script on multiple GPUs, leveraging Accelerate.

[pix2pix] Add Accelerator support

---

huggan/pytorch/huggan_mixin.py
huggan/pytorch/lightweight_gan/cli.py
huggan/pytorch/lightweight_gan/lightweight_gan.py
huggan/utils/hub.py
requirements.txt

This PR aims to add the ability to push lightweight GAN to the hub periodically every `save_every` steps. It will also include misc bugfixes as I run across them.

Add Push To Hub functionality for Lightweight GAN

---

huggan/pytorch/lightweight_gan/lightweight_gan.py

This PR fixes the issue with blured images while generating out of training.

fix: Lightweight GAN Blur

---

computer-vision-study-group/README.md

[Add]: Intro to NeRF slides

---

computer-vision-study-group/README.md

This PR adds the notebook used during the CV study group on Discord.

Add notebook

---

computer-vision-study-group/README.md

add MAE slides in CV study group

---

whisper-fine-tuning-sprint/README.md

**Motivation**: One-stop resource for all the resources and instructions for the sprint.
**Intended audience**: Participants for the Whisper community event and future developers/ hobbyist chancing upon fine-tuning guides for the event.
**Estimated date for release**: Monday, 21st November 2022

[Whisper fine-tuning sprint] README updates + organisation

---

whisper-fine-tuning-event/README.md

[WFTE] Sec Machine

---

whisper-fine-tuning-event/fine-tune-whisper-streaming.ipynb
whisper-fine-tuning-event/run_speech_recognition_seq2seq_streaming.py

Updates ipynb according to the insightful comments from @polinaeterna in the PR blog post https://github.com/huggingface/blog/pull/636

[WFTE] Streaming explanation

---

whisper-fine-tuning-event/README.md
whisper-fine-tuning-event/fine-tune-whisper-streaming.ipynb
whisper-fine-tuning-event/interleave_streaming_datasets.ipynb
whisper-fine-tuning-event/run_speech_recognition_seq2seq_streaming.py

[WFTE] Add example for interleaving datasets

---

whisper-fine-tuning-event/run_eval_whisper_streaming.py

Add functionality push metrics to hub at the end of evaluation

Add push to hub for metrics

---

keras-dreambooth-sprint/README.md
sklearn-sprint/guidelines.md

Fixed sklearn links and added keras guide

---

keras-dreambooth-sprint/README.md
keras-dreambooth-sprint/compute-with-lambda.md

@osanseviero @sayakpaul I think this will be easier to review. I addressed nits and comments we had a consensus on.

Addressed comments

---

keras-dreambooth-sprint/README.md

I can revert the warning. My main concern was users going through everything and not realizing until after training a model that there were categories.

Fix headings and add a warning about categories

---

keras-dreambooth-sprint/compute-with-lambda.md

Add cuda installation to the guide

---

keras-dreambooth-sprint/compute-with-lambda.md

@merveenoyan 
As disussed on discord  I am creating a PR for  updated info on setting up a LmabdaLabs server for Keras Dreambooth Sprint

PR Updated keras lambda setup info

---

jax-controlnet-sprint/README.md
jax-controlnet-sprint/training_scripts/train_controlnet_flax.py

Some stuff is copy-pasted from https://github.com/huggingface/transformers/tree/main/examples/research_projects/jax-projects and https://github.com/huggingface/diffusers/tree/main/examples/controlnet.

Populate README with training example

---

jax-controlnet-sprint/README.md
jax-controlnet-sprint/training_scripts/train_controlnet_flax.py

updated the training script so that people can log the training to their team account 
also want to use this PR to update the instructions on how to create free wandb team account (waiting for inputs from wandb team)

[WIP] add wandb team

---

jax-controlnet-sprint/README.md

add troubleshoot section

---

jax-controlnet-sprint/README.md

Otherwise, the section doesn't render appropriately.

Update README.md to fix the Spaces section

---

jax-controlnet-sprint/README.md

add a few sentence to explain `from_pt` argument in training script

explain --from_pt

---

jax-controlnet-sprint/README.md

Update README.md to include jury and winners :) 

---

open-source-ai-game-jam/README.md

Update Game Jam Event

---

computer-vision-study-group/README.md
computer-vision-study-group/Sessions/Blip2.md
computer-vision-study-group/Sessions/Fiber.md
computer-vision-study-group/Sessions/FlexiViT.md
computer-vision-study-group/Sessions/HFVisionEcosystem.md
computer-vision-study-group/Sessions/HowDoVisionTransformersWork.md
computer-vision-study-group/Sessions/MaskedAutoEncoders.md
computer-vision-study-group/Sessions/NeuralRadianceFields.md
computer-vision-study-group/Sessions/PolarizedSelfAttention.md
computer-vision-study-group/Sessions/SwinTransformer.md

Hey all,
I updated the overview of the CV study group a bit and brought it up to date :slightly_smiling_face:

updated CV Study Group docs

---

open-source-ai-game-jam/README.md

Update Game Jam
